baseURL = 'https://spout2pw.lina.yt/'
languageCode = 'en-us'
title = 'Spout2PW & OBS-PWVideo'
theme = "hugo-theme-monochrome"

[params]
author = "Hoshino Lina"
enable_toc = false

[markup.goldmark.renderer]
unsafe= true

[caches]
[caches.images]
dir = ':cacheDir/images'


